apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalogue
  annotations:
    github.com/project-slug: seal-demo/catalogue
spec:
  type: other
  lifecycle: unknown
  owner: team-b
  dependencyOf:
    - component:carts
  providesApis:
    - catalogue-api
